### PR TITLE
Refactor code to avoid errors in CheckStyle task

### PR DESCRIPTION
**Pull request by acasadoquijada**
Hi!

I refactored the code as requested in #32 to ensure it adheres to conventions set by CheckStyle.

Let me know if you want me to make more changes

Best regards,
Alex

### CODE REVIEW

**Comment by acasadoquijada** [comment]
I performed all the changes by myself. I've reviewed the project and it under the account MSU Denver CS. So I guess that by one of my teammates you mean a colleague from the University, Am I right? 

I'm afraid I'm not a member of the MSU Denver CS so I cannot ask a teammate to review the changes

Please let me know if there is something I can do to help you review the impact of the changes to the project

**Comment by jody** [comment]
I apologize, I thought you might have a closer connection to others working on the project!  This project is relatively new as open source and is sadly lacking information for contributors, noticeably any "How to Contribute", "Contribution Workflow", or "Development Conventions".

The current protocol is for potential contributors to "request" to claim an issue (by making a comment to the issue) which then results in potential assignment to that issue.

In this instance, User Story #32 is an "Epic", so there are component stories (#33, #34, #35) and each is _already assigned_.

Another concern is actually due to a weakness associated with User Story #32.  In particular, the Assessment Criteria over-simplifies the intent to simply making errors not be reported.  It needs clarification of the intent of such code modifications.  For example, the use of "TODO:" is desired and part of the coding convention.  (Checkstyle is being used to ensure that any embedded TODO comments are well identified and reported.)  Thus, "fixing" those Checkstyle errors requires changes to the code implementation, not just changing "TODO:" to some other string (e.g., "TO DO:"), which just hides the shortcoming without improving the product.

I apologize for the lack of documentation even at this early stage of the project!!

**Comment by acasadoquijada** [comment]
Don't worry @jody!

In that case, I can undo the changes to the TODO comments to ensure that they are identified as you mentioned.

Besides, as #33, #34, #35 are already assigned, do you need more help with the Checkstyle error reporting?

Just let me know how I can help :)

**Comment by jody** [comment]
I appreciate your understanding!

Let's see how thing go over the next week.  The issues currently in progress are being worked on by undergraduate students relatively new to software development.  The semester ends in a couple of weeks, so either those issues will be resolved or they will go back into the "To Do" column of the [project board](https://github.com/MetroCS/imagelab/projects/1).

**Pull request closed without merging**
