### PR TITLE
Gradle build is now compliant with imagelab "README"

### PR DESCRIPTION
**Pull request by jstrelka**
ISSUE: #5 

Gradle now recognizes and builds the Run.java file in the root project directory. The Run.java file is included in the ./gradlew build task, as well as the ./gradlew clean task. The './gradlew run' task now searches for the Run.class as the applications mainClassName.
Best!

### CODE REVIEW

**Comment by jody** [comment]
Commit message indicates that the _"jar file is **not** copied onto project root dir"_.  Is that correct?

**Comment by jstrelka** [comment]
There was a grammatical error in my latest commit message. The not is supposed to be now, the .jar file does get copied into the root directory.

**Comment by jstrelka** [comment]
The clean task does remove all .class files and the generated build directory.

**Comment by jstrelka** [comment]
@GracchusMinor @corywilson88 @DendeLime @BlackCanyonDreams @TImmyTurner123 @jstrelka Please take a moment to test and run the changes to the build.gradle file and leave explicit comments on you findings. Best!

**Comment by jstrelka** [comment]
The build has been updated for the project root directory to be recognized in mac OS's. The ./gradlew build command should no longer stall at the compileJava task.

**Comment by jody** [comment]
> The build has been updated for the project root directory to be recognized in mac OS's. The ./gradlew build command should no longer stall at the compileJava task.

Is this just a Mac OSX-specific issue and update?
For which operating systems has this build been tested?

**Comment by jstrelka** [comment]
It has been tested on both mac OS and Windows OS. Mac did not recognized "/" as root project directory and thought it was the actual root directory. We have rectified the issue by using a gradle variable project.projectDir to work in both MAC and Windows OS.

**Comment by jody** [comment]
I think we at least need a Linux variant tested.  (My initial assumption is that fixing the build for OSX unix also fixes it for Linux systems; however, that needs to be verified.)

**Comment by jstrelka** [comment]
Verified build is successful in Windows 10, MAC OSX, and Linux (Ubuntu Bionic 16.04).

**Pull request merged**
