### PR TITLE
Put ImgProviders play method in a thread

### PR DESCRIPTION
**Pull request by seboss123**
Allows the user to still retain menu item and title bar button functionality while audio is playing

### CODE REVIEW

**Comment by jody** [comment]
Is this associated with an issue?  If so, please reference it explicitly (by # ).

**Comment by seboss123** [comment]
This is associated with the issue #13

**Comment by seboss123** [comment]
I removed the deprecated method because it was not requested as a feature.

**Comment by seboss123** [comment]
Rebase was completed. PR now only show changes to one file.

**Pull request merged**
