### PR TITLE
Initial Gradle build completed.

### PR DESCRIPTION
**Pull request by jstrelka**
ISSUE: #5 

The gradle build is currently compiling and able to run the application. I have also included and configured jacoco in the build for our needs of code coverage analysis. 
Best!

### CODE REVIEW

**Comment by jody** [comment]
If this PR is associated with a bug or user story, please reference that issue explicitly so that the relationship is documented (and automatically linked by GitHub).

**Comment by jstrelka** [comment]
ISSUE: #5 

BlueJ functionality has been retained by moving package.bluej to the src/main/java folder. The excess sample source code files have been removed from src/main/java and src/test/java.

**Comment by jstrelka** [comment]
ISSUE: #5 
All source code has been put back into the project root directory and gradle build has been updated to adapt to the source code move.

**Comment by jstrelka** [comment]
ISSUE: #5
BlueJ updates the package.bluej file every time a user opens the project in BlueJ. 
I have reverted the auto-generated changes to the package.bluej file to match the originial.

**Comment by jstrelka** [comment]
Files changed now displays seven excluding package.bluej file.

**Pull request merged**
