### PR TITLE
Changes to the project to allow for Filter directory selection

### PR DESCRIPTION
**Pull request by pedroflima**
Pull request to address issue #1 
A configuration for filter folder is now available under the File menu.

### CODE REVIEW

**Review by jody — CHANGES_REQUESTED** [review]
In testing, I can see the new menu item in the File menu.  However, I am unable to select a folder from the popup chooser.  (Also, this placement of the menu item is not intuitive.)

JVM:        11.0.6 (AdoptOpenJDK 11.0.6+10)
OS:           Mac OS X 10.15.7 x86_64

**Comment by jody** [comment]
The ability to select a directory is a configuration of JFileChooser.
See: https://docs.oracle.com/javase/tutorial/uiswing/components/filechooser.html

Not sure if that will address the problem I'm seeing, but it will improve the user experience.

**Comment by pedroflima** [comment]
Dr @jody, the Pull Request has been amended with 1 more commit containing changes to use the JFileChooser, as last suggested. Testing on MacOS has not yet been possible (the team does not have boxes, physical or virtual, running MacOS)

**Review by jody — CHANGES_REQUESTED** [review]
There appear to be some undesired side-effects.  Please check that this code isn't sending data to stdout and/or stderr inappropriately.

More importantly, I'm confused about the requirements for filters appearing in the alternative directory.  In particular, what are the constraints on the package in which they appear?  How are such filters intended to be compiled?  These questions may indicate that the requirement (User Story #1) wasn't fully fleshed out and that the design wasn't adequately vetted, before this development proceeded.

I've just reviewed the associated issue (#1) and see that it is labeled as an **epic** and that the Acceptance Criteria checkbox isn't ticked.  Both of those suggest that more initial work on _specification_ are needed.  My apologies for letting this PR go this long without realizing that there hadn't been adequate specification or design.

**Comment by pedroflima** [comment]
Dr. @jody,

As we discussed, I will close this pull request and add information regarding the added complexity to issue #1

**Pull request closed without merging**
