### PR TITLE
Proposed resolution to issue # 83 (Invalid File type)

### LINKED ISSUE #83: [UserStory] Notify Users of an unrecognizable file type and let user select a new file
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _Imagelab user_
**I want**  _to be notified that the type of the file I selected was not recognized by Imagelab and I am allowed to select a new file_  
**so that**  _I know why the file wasn't opened and I'm able to continue using Imagelab in the same instance._  

## Acceptance Criteria

* _When a user selects a file type not recognized by Imagelab they are notified that the file type is not recognized by Imagelab_
* _After a user is notified that a file type was not recognized, the user is able to select a new file_

### Scenario 1
**Given**  _a user in Imagelab selects an image file by navigating to File > Open_  
**when**  _a file type not recognized by Imagelab is selected_  
**then**  _the user is notified that the file type is unrecognized and the user is able to select another file._

### PR DESCRIPTION
**Pull request by esundbla**
The addition of a while loop in the action listener of  [ImageLab](https://github.com/MetroCS/imagelab/blob/cf69b8bb5e4f5917d97e701b33a4c55f593aa260/imagelab/ImageLab.java#L283-L299) to [Updated](https://github.com/Nugget3-14/imagelab-1/blob/5465ca28c10045cfb54d0a9c6944eb9173c9d06c/imagelab/ImageLab.java#L283-L305). Will resolve freezing on selection of invalid file types brought up in issue #83 .The fix allows for re selection until valid file type is selected.
- #83

Contributors:  @esundbla code and pull request. @babybeans, and @noah-fullerton for code review and verification.

### CODE REVIEW

**Comment by jody** [comment]
Just glancing at the PR, I'm wondering why there are **nine** files changed.

It would also be good see documented assessment of the quality of the changes, such as the outcomes of tests and code checks.

I'm going to hold off on an actual review until your team has had a chance to review the appropriateness of all changes associated with this PR and some quality assessment.

**Comment by esundbla** [comment]
We had a chance now as a team @Nugget3-14, to review the PR.  After cleaning unnecessary file changes related to individual IDE's. We now believe the PR is ready to merge!

**Comment by jody** [comment]
This PR appears to result in multiple regressions of the code base.
These were revealed via unit testing, checking coding conventions, and attempting to run the product.

**Unit Testing**
Before applying this PR, _JUnit_ reports **no** errors.
After applying this PR, _JUnit_ reports **one** error.

**Coding Conventions**
Before applying this PR, _Checkstyle_ reports
• **9** errors in ImgProvider
• **7** errors in ImageLab
After applying this PR, _Checkstyle_ reports
• **18** errors in ImgProvider
• **17** errors in ImageLab

**Runtime Behavior**
After applying this PR, running the program via
`./gradlew run`
**disallows** opening image file types that were **previously recognized** by the product.


**Please fix problems and squash commits.  Thank you!**
___
Notify: @Nugget3-14 @esundbla @babybeans @noah-fullerton

**Review by jody — CHANGES_REQUESTED** [review]
See: https://github.com/MetroCS/imagelab/issues/110#issuecomment-1088211349

**Pull request closed without merging**
